author: "Eko Susilo"
category: "admin"
summary: "Filtering packet message"
home: "https://github.com/iamucil/ejabberd-elixir-modules/tree/master/"
url: "git@github.com:iamucil/ejabberd-elixir-modules.git"
